---
# host_vars file for rsync-backup


###[targets] vars

#backup location on [targets]
# backup location clould be multiple targets like: "/etc/nginx /home/myuser"
backup_location: /

#backup frequency in crond format
backupfreq: 0 12 * * 2

# [targets] service username
backup_user: service-backup-rsync

#Rsync script variables
# path might differ from flavor to flavor. Edit these if that is the case.
sudopath: /usr/bin/sudo
rsyncpath: /usr/bin/rsync

#Define retention rate with following variable
# Tip change to <"10 days ago"> for a 10 days retention rate
OLDBACKUP: date -d "2 days ago" +"%Y%m%d"

#######################################################

###[backup_servers] vars

#Persistant storage on [backup_server]
# where backup will be stored. Possible to have 
#different pers_storage for multiple backup_Servers
pers_storage: /mnt/rustdisk/backup-rsync

# [backup_servers] service username 
backup_user_backupserver: service-backup-rsync

#SSH port [backup_servers]
sshport: 22